Iter2
kamencov/goph-keeper pull request #2
Opened 2024-12-23 17:24 UTC by kamencov

2024-12-23 17:25 UTC, kamencov commented
# goph-keeper

Шаги:

1. Сначала требуется запустить сервер

        go run cmd/service/main.go

2. Запускаем клиента

         go run cmd/client/main.go

В сервисе клиенте реализованы метода:

- **Register** - регистрирует клиента через сервис gRPC.
- **Auth** - авторизация клиента через сервис gRPC, получает token и хранит у клиента.
- **Quite** - выходит из клиента.

После авторизации открывается возможность сохранять, искать, удалять:

1. **Creadentials** - хранит данные в виде resource, login, password:

**Save** - реализован.

**Find** - нет реализации.

**Deleted** - нет реализации.

**Quite** - выходит из клиента.

2. **Text** - хранит данные в виде text:

**Save** - нет реализации.

**Find** - нет реализации.

**Deleted** - нет реализации.

**Quite** - выходит из клиента.

3. **Binary** - хранит данные в виде binary:

**Save** - нет реализации.

**Find** - нет реализации.

**Deleted** - нет реализации.

**Quite** - выходит из клиента.

4. **Cards** - хранит данные в виде card number:

**Save** - нет реализации.

**Find** - нет реализации.

**Deleted** - нет реализации.

**Quite** - выходит из клиента.

2025-01-10 04:15 UTC, vokinneberg requested changes
Ну вот мы и подобрались к финальному выпускному проекту! 🎉 По традиции поздравляю с первым ревью, желаю удачи 🍀  Отмечу сильные стороны твоего PR, а также сделаю несколько комментариев по поводу того, на что стоит обратить внимание и что можно улучшить. 🤓

**Сильные стороны твоего PR:**

- Спасибо за реализацию [[README.md](http://readme.md/)](http://readme.md/) файла с пояснением! 👍
- 👍 за реализацю graceful shutdown!

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Для того чтобы сделать README немного более содержательным, я бы рекомендовал структурировать его следующим образом:
    - Можно добавить раздел с описанием сервиса и его базовой функциональности.
    - Добавить беджи с тестовым покрытием и https://goreportcard.com/
    - Добавить раздел с подробным описанием того, как запускать сервис. Сюда может входить описание выполнения миграций БД, установки флагов или переменных окружения и так далее.
    - Раздел с описанием того, как тестировать сервис.
    - Раздел с описанием того, какие сторонние пакеты использовались для реализации с их версиями.
- Стоит поработать над форматированием кода.
- Есть проблема с запуском сервера — если код на строке 83 или строке 90 выполнится с ошибкой, горутина вернёт управление, а приложение останется работать и при этом не будет ничего делать.
- Стоит поработать над тестами для приложения. Их маловато, и они сейчас выполняются с ошибкой.
- Стоит поработать над именованием интерфейсов.
- Я не очень вижу смысл в создании слоёв, которые ничего по сути не делают. Возможно, это изменится в будущем, но сейчас у этого слоя нет никакой функции — по сути он только усложняет структуру программы. Стоит избавиться от слоёв-прокси.
- В БД не хватает индексов.
- Честно говоря, не вижу необходимости мельчить, вынося каждый метод в отдельный файл. Это усложняет чтение и навигацию по коду. В одном файле было бы удобнее ориентироваться, на мой взгляд.

2025-01-10 04:15 UTC, vokinneberg commented on README.md
> +# goph-keeper
Спасибо за реализацию README.md файла с пояснением! 👍  Для того чтобы сделать README немного более содержательным, я бы рекомендовал структурировать его следующим образом:

- Можно добавить раздел с описанием сервиса и его базовой функциональности.
- Добавить беджи с тестовым покрытием и https://goreportcard.com/
- Добавить раздел с подробным описанием того, как запускать сервис. Сюда может входить описание выполнения миграций БД, установки флагов или переменных окружения и так далее.
- Раздел с описанием того, как тестировать сервис.
- Раздел с описанием того, какие сторонние пакеты использовались для реализации с их версиями.

2025-01-10 04:15 UTC, vokinneberg commented on logfile.log
> +time=2024-12-23T22:55:12.728+03:00 level=INFO msg="connected to database"
Не стоит коммитить logfile в репозиторий.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/run.go
> +const host = "localhost:8081"
Я бы предложил сделать название более информативнывм, в противном случае оно теряется. 
```suggestion
const defaultHost = "localhost:8081"
```

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/run.go
> +	file, err := os.Create("logfile.log")
Не совсем понятно, почему выбран такой безальтернативный вариант логирования в файл. Я бы предложил реализовать логирования в стандартный вывод по-умолчанию и реализовать возможность перенаправлять лог файл, если указано его имя, хотя на мой взгляд проще просто перенаправить вывод.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/run.go
> +		panic(err)
Не рекомендую паниковать во внутренних компонентах. У нас эта функция возвращает ошибку - почему бы не вернуть ее в вызывающий код, который ее обработает и решит, что с ней делать.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/run.go
> +
Здесь почему-то ничего не происходить. Возможно стоит вызвать логирвоание?

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/run.go
> +	//newWorker := workers.NewWorker(nil)
Я так понял это еще предстоит релизовать?

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/handlers/auth/handlers.go
> +type service interface {
Можно попробовать использовать нотацию, которую рекомендуют сами разработчики Go для интерфейсов из одного метода - имя метода + er.
```suggestion
type tokenSaver interface {
```

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/handlers/auth/handlers.go
> +	registerClient := v1_pd.NewRegisterClient(conn)
А можем мы создать клиента один раз в момент инициализации приложения и переиспользовать его, а не создавать каждый раз новый?

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/handlers/auth/handlers.go
> +	authClient := v1_pd.NewAuthClient(conn)
Тот же самый вопрос по поводу клиента для авторизации?

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/handlers/save/save.go
> +	ErrNotEmpty = fmt.Errorf("empty data entered")
Имелось ввиду Error Empty, я думаю?
```suggestion
	ErrEmpty = fmt.Errorf("empty data entered")
```

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/handlers/save/save.go
> +		fmt.Println("data is empty")
Здесь тоже стоит использовать logger.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/handlers/save/save.go
> +func (h *Handler) PostBinaryData(ctx context.Context, data string) error {
Если данные binary, стоит использовать тип `[]byte` вместо `string`.
```suggestion
func (h *Handler) PostBinaryData(ctx context.Context, data []byte) error {
```

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/handlers/save/save.go
> +type serviceCredentials interface {
Правило, которое я описал выше применимо к этим интерфейсам так же.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/cli/run.go
> +		panic(err)
То же самое - не стоит тут паниковать, стоит вернуть ошибку в `main` и там ее обработать.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/cli/auth_button.go
> +	form.SetBorder(true).SetTitle("Зарегистрироваться").SetTitleAlign(tview.AlignLeft)
Мне кажется, когда часть интерфейса на латинице, а часть на кириллице это не очень консистентно и, как  следствие красиво. Стоит использовать либо одно, либо другое.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/cli/binary_button.go
> +		if buttonLabel == "Save" {
Возможно тут лучше подойдет switch-case?

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/cli/buttons.go
> +	form.
Здесь как-будто не хватает форматирования?

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/cli/errors_cli.go
> +				pages.SwitchToPage("Register")
Если здесь сделать `return`, то `else` можно будет убрать.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/cli/errors_cli.go
> +				pages.SwitchToPage("Register")
Если здесь сделать `return`, то `else` можно будет убрать.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/cli/get_all_button.go
> +						panic(err)
Не стоит тут паниковать тоже, это приведет в немедленному выходу из приложения - думаю это не то, чего мы хотим в случае ошибки.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/client/cli/get_all_button.go
> +					panic(err)
🙅

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/service/run.go
> +	const op = "run.service.app"
 Константу стоит вынести за пределы функции.

2025-01-10 04:15 UTC, vokinneberg commented on cmd/service/main.go
> +		panic(err)
Все же я бы рекомендовал использовать либо `log.Fatal(...)`  либо `os.Exit(...)` для выхода из приложения, особенно если нам не нужно выполнять `defer` блоки при выходе. Это более конвенциональный способ выхода.

2025-01-10 04:15 UTC, vokinneberg commented on cmd/service/main.go
> +	case envLocal:
Мне кажется это слишком сложно - можно просто установить уровень логирования по-умолчанию в `slog.LevelInfo` и для `envLocal` менять его на `slog.LevelDebug`.

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/service/run.go
> +
Логирование?

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/service/run.go
> +	signal.Notify(stop, syscall.SIGTERM, syscall.SIGINT)
👍 за реализацю graceful shutdown! Тем не менее есть проблема - если код на строке 83 или строке 90 выполниться с ошибкой, горутина вернет управление, а приложение останется работать и при этом не будет ничего делать;

2025-01-10 04:15 UTC, vokinneberg commented on internal/api/service/run.go
> +		return
Этот `return` в общем-то лишний.

2025-01-10 04:15 UTC, vokinneberg commented on internal/grpc/auth/handlers.go
> +		if errors.Is(err, auth.ErrNotFoundLogin) {
👍 за реализацию кастомных ошибок!

2025-01-10 04:15 UTC, vokinneberg commented on internal/services/client/auth_client/auth.go
> +		if !errors.Is(err, sql.ErrNoRows) {
Тут не совсем понял - по-моему условие должно наоборот срабатывать если мы не получили ни одной записи?
```suggestion
		if errors.Is(err, sql.ErrNoRows) {
```

2025-01-10 04:15 UTC, vokinneberg commented on internal/services/server/auth/auth.go
> +		return Tokens{}, ErrNotFoundLogin
Здесь можно было бы возвращать `nil` если использовать указатель, как возвращаемый тип?

2025-01-10 04:15 UTC, vokinneberg commented on internal/services/server/cards/save.go
> +	return s.storage.SaveCards(ctx, userID, cards)
 Я не очень вижу смысл в создании слоев, которые ничего по сути не делают. Возможно это изменится в будущем, но сейчас у этого слоя нет никакой функции - по сути он только усложняет структуру программы. Стоит от него избавится.

2025-01-10 04:15 UTC, vokinneberg commented on internal/services/server/credentials/save.go
> +	err := s.storage.SaveLoginAndPasswordInCredentials(ctx, userID, resource, login, password)
То же самое - эта функция ничего не делает. Зачем она?

2025-01-10 04:15 UTC, vokinneberg commented on internal/storage/postgresql/postgresql.go
> +	path := os.Getenv("DATABASE_DSN")
Лучше передать эту переменную окружения извне в качестве параметра. Не стоит завязываться жестко на переменные окружения, вдруг захочется реализовать настройку приложения через флаги или из файла?

2025-01-10 04:15 UTC, vokinneberg commented on internal/storage/postgresql/postgresql.go
> +	err = p.applyMigrations()
Я бы посоветовал сделать этот вызов опциональным.

2025-01-10 04:15 UTC, vokinneberg commented on internal/storage/postgresql/postgresql.go
> +func (p *Postgresql) CheckUser(ctx context.Context, login string) error {
Мне кажется, что проверка существования пользователя это как раз ответственность сервисного слоя, а ответственность слоя доступа к данным не принимать решения, а возвращать данные из хранилища. В этом случае мы переносим бизнес-логику на служебный слой и таким образом нарушаем single responsibility principle.

2025-01-10 04:15 UTC, vokinneberg commented on internal/storage/postgresql/postgresql.go
> +func (p *Postgresql) CheckPassword(login string) (string, bool) {
То же самое касается проверка пароля. Тут наименование метода не совпадает с тем, что он делает. Я бы советовал просто вернуть данные пользователя по логину, а проверки стоит выполнять в сервисном слое.

2025-01-10 04:15 UTC, vokinneberg commented on internal/services/client/credentials_client/save.go
> +func (s *ServiceClient) SaveLoginAndPassword(ctx context.Context, token, resource, login, password string) error {
Честно говоря не вижу необходимости так мельчить вынося каждый метод в отдельный файл. Это усложняем чтение и навигацию по коду. В одном файле было бы удобнее ориентироваться на мой взгляд.

2025-01-12 11:52 UTC, kamencov commented on internal/api/client/run.go
> +	file, err := os.Create("logfile.log")
потому-что у меня cli использует ввод, который не дает мне возможности отслеживать логи

2025-01-12 11:52 UTC, kamencov commented on logfile.log
> +time=2024-12-23T22:55:12.728+03:00 level=INFO msg="connected to database"
убра

2025-01-12 11:53 UTC, kamencov commented on internal/api/client/run.go
> +const host = "localhost:8081"
исправил

2025-01-12 11:54 UTC, kamencov commented on internal/api/client/run.go
> +		panic(err)
исправил

2025-01-19 17:04 UTC, merged